backend:
  name: git-gateway
  branch: master

media_folder: content/images
site_url: https://fuerteventuradogrescue.netlify.app
logo_url: https://fuerteventuradogrescue.netlify.app/static/e51369760fde3f62aab3cbd7692ec889/dfcae/logo.png
collections:
- name: articles
  label: Articles
  label_singular: Article
  folder: articles
  create: true
  editor:
    preview: false
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  path: '{{slug}}/index'
  media_folder: ''
  fields:
    - label: Title
      name: title
      widget: string
      pattern: ['.{2,30}', "Must be between 2 and 30 characters"]
    - label: Featured Image
      name: featured_image
      widget: image
      default: /images/default_article.png
    - label: Date
      name: date
      widget: datetime
    - label: Language
      name: language
      widget: select
      options:
        - { label: "English", value: "en" }
        - { label: "Español", value: "es" }
        - { label: "Deutsch", value: "de" }
        - { label: "Italiano", value: "it" }
        - { label: "Français", value: "fr" }
      default: "en"
    - label: Body
      name: body
      widget: markdown
- name: dogs
  label: Dogs
  label_singular: Dog
  folder: dogs
  create: true
  editor:
    preview: false
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  path: '{{slug}}/index'
  media_folder: ''
  fields:
    - label: Name
      name: title
      widget: string
      pattern: ['.{2,14}', "Must be between 2 and 14 characters"]
    - label: Sex
      name: sex
      widget: select
      options:
        - { label: "Male", value: "0" }
        - { label: "Female", value: "1"}
    - label: Breed
      name: breed
      widget: string
      pattern: ['.{2,20}', "Must be between 2 and 20 characters"]
    - label: Date of birth
      name: date_of_birth
      widget: datetime
    - label: Date entered
      name: date_entered
      widget: datetime
    - label: Location
      name: location
      widget: select
      options:
        - { label: "Shelter", value: "0" }
        - { label: "Foster", value: "1" }
        - { label: "Other", value: "2" }
      default: "0"
    - label: Summary
      name: summary
      widget: object
      hint: This is the text that shows on the dog listings page
      fields:
        - { label: "English", name: "en", widget: text, pattern: ['.{2,60}', "Must be between 2 and 60 characters"] }
        - { label: "Español", name: "es", widget: text, pattern: ['.{2,60}', "Must be between 2 and 60 characters"] }
        - { label: "Deutsch", name: "de", widget: text, pattern: ['.{2,60}', "Must be between 2 and 60 characters"] }
        - { label: "Italiano", name: "it", widget: text, pattern: ['.{2,60}', "Must be between 2 and 60 characters"] }
        - { label: "Français", name: "fr", widget: text, pattern: ['.{2,60}', "Must be between 2 and 60 characters"] }
    - label: Main image
      name: main_image
      widget: image
    - label: Images
      name: images
      widget: list
      field: { label: Image, name: image, widget: image }
      required: false
    - label: YouTube link
      name: youtube
      required: false
      widget: string
    - label: PPP?
      name: ppp
      widget: select
      options:
        - { label: "No", value: "0" }
        - { label: "Yes", value: "1" }
        - { label: "TBC", value: "2" }
    - label: Dog friendly?
      name: dog_friendly
      widget: select
      options:
        - { label: "No", value: "0" }
        - { label: "Yes", value: "1" }
        - { label: "TBC", value: "2" }
    - label: Cat friendly?
      name: cat_friendly
      widget: select
      options:
        - { label: "No", value: "0" }
        - { label: "Yes", value: "1" }
        - { label: "TBC", value: "2" }
    - label: Family friendly?
      name: family_friendly
      widget: select
      options:
        - { label: "No", value: "0" }
        - { label: "Yes", value: "1" }
        - { label: "TBC", value: "2" }
    - label: Sterilised?
      name: sterilised
      widget: select
      options:
        - { label: "No", value: "0" }
        - { label: "Yes", value: "1" }
    - label: Description
      name: description
      widget: object
      fields:
        - { label: "English", name: "en", widget: markdown, buttons: ["bold", "italic", "link"], editorComponents: [] }
        - { label: "Español", name: "es", widget: markdown, buttons: ["bold", "italic", "link"], editorComponents: [] }
        - { label: "Deutsch", name: "de", widget: markdown, buttons: ["bold", "italic", "link"], editorComponents: [] }
        - { label: "Italiano", name: "it", widget: markdown, buttons: ["bold", "italic", "link"], editorComponents: [] }
        - { label: "Français", name: "fr", widget: markdown, buttons: ["bold", "italic", "link"], editorComponents: [] }
- label: "Admin"
  name: "admin"
  editor:
    preview: false
  files:
    - label: "Social and contact"
      name: "links"
      file: "content/links.md"
      fields:
        - { label: "Email address", name: email, widget: string }
        - { label: "Facebook username", name: facebook, widget: string }
        - { label: "Instagram username", name: instagram, widget: string }
    - label: "Opening hours"
      name: "hours"
      file: "content/hours.md"
      fields:
        - { label: "Thursdays", name: thursdays, widget: string }
        - { label: "Weekends", name: weekends, widget: string }
        - { label: "Holidays", name: holidays, widget: string }
- label: "Pages"
  name: "pages"
  media_folder: "./images"
  public_folder: "images"
  editor:
    preview: false
  files:
    - label: "Who are we?"
      name: "whoarewe"
      file: "content/whoarewe.md"
      fields:
        - label: "Image"
          name: image
          widget: image
        - label: "English"
          name: en
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Español"
          name: es
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Deutsch"
          name: de
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Italiano"
          name: it
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Français"
          name: fr
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
    - label: "Adopt"
      name: "adopt"
      file: "content/adopt.md"
      fields:
        - label: "Image"
          name: image
          widget: image
        - label: "English"
          name: en
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Español"
          name: es
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Deutsch"
          name: de
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Italiano"
          name: it
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Français"
          name: fr
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
    - label: "Foster"
      name: "foster"
      file: "content/foster.md"
      fields:
        - label: "Image"
          name: image
          widget: image
        - label: "English"
          name: en
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Español"
          name: es
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Deutsch"
          name: de
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Italiano"
          name: it
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Français"
          name: fr
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
    - label: "Donate"
      name: "donate"
      file: "content/donate.md"
      fields:
        - label: "Image"
          name: image
          widget: image
        - label: "English"
          name: en
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Español"
          name: es
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Deutsch"
          name: de
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Italiano"
          name: it
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Français"
          name: fr
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
    - label: "Volunteer"
      name: "volunteer"
      file: "content/volunteer.md"
      fields:
        - label: "Image"
          name: image
          widget: image
        - label: "English"
          name: en
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Español"
          name: es
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Deutsch"
          name: de
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Italiano"
          name: it
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Français"
          name: fr
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
    - label: "Lost or abandoned text"
      name: "lostorabandoned"
      file: "content/lostorabandoned.md"
      fields:
        - label: "English"
          name: en
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Español"
          name: es
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Deutsch"
          name: de
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Italiano"
          name: it
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
        - label: "Français"
          name: fr
          widget: markdown
          buttons: ["bold", "italic", "link"]
          editorComponents: []
