export const SET_POPUP = "SET_POPUP"
export const SET_LANGUAGE_DIALOG = "SET_LANGUAGE_DIALOG"
export const SET_LANGUAGE = "SET_LANGUAGE"
export const SET_NAV = "SET_NAV"
export const SET_REDIRECT = "SET_REDIRECT"
export const SET_MAIN_IMAGE = "SET_MAIN_IMAGE"
